### PR TITLE
Update to hide attributes in 0.115

### PR DESCRIPTION
**Pull request by CAB426**
0.115 changed the name of the `more-info` element.  It now changes depending on the entity type.  All elements start with `more-info-` so I added in a loop through the node list to find the name that starts with `more-info-` and use that to find the attributes.

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
this PR is now ready to test? (the other PR was closed, so I am 'holding of' still ;-)

**Comment by CAB426** [comment]
This one is ready to test.  :) 

I closed the other one so there wasn't any confusion.  Don't have all the entity types in my dev environment.  Looked good there, not so much in prod.

**Comment by Mariusthvdb** [comment]
cool, will test. please describe for me what you saw in 115 before the edit in custom-ui, and what this Pr changes? So I can test correctly.

**Comment by CAB426** [comment]
That is exactly what I was seeing.  Much like the change to 113 broke hiding attributes, so did 115.  I had to handle the changes in 115.  It should now hide attributes in 115 as it does it 113-114, and < 113.

**Comment by Mariusthvdb** [comment]
ok, thanks, a quick test here shows that is indeed happening correctly now, on 115 and 114.4 

Great contribution once again. 
1 thing: the line change on 1306 is somewhat strange since it changes to a code already in place?

```
if (!window.location.pathname.startsWith("/config"))
```
is current code, so no need to change that.

I have adapted the additional lines manually in the file and update accordingly.
Updated the date field too, so this reflects in inspector console and Info page.

Thanks again for a great contribution! Together we can keep Custom-ui up to date and functional going forward.

**Comment by CAB426** [comment]
@Mariusthvdb That `config/info` must've been floating around in there when I took a quick look at the e.push issue.  Sorry about that.  Glad that was resolved as well!

**Comment by Mariusthvdb** [comment]
could it be the 
```
hide_attributes:
  - all
```

is no longer functional?

**Comment by CAB426** [comment]
Is it not working on your end? It is working correctly for me on 0.115.0 and 0.115.1.

**Pull request closed without merging**
