### PR TITLE
Update to handle 0.117 changes for More-Info popups

### PR DESCRIPTION
**Pull request by CAB426**
0.117 introduced capitalization in Attribute names for More-Info popups.  Handled by adding in .toLowerCase() in if statement.  Updated version to 20201102

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
Thanks.
Could you explain/describe what is the issue? To be honest, I don’t see an issue in the more-info pop-ups?

**Comment by CAB426** [comment]
The attributes were no longer hidden in the more-info popup (as reported by you on the [closed PR](https://github.com/Mariusthvdb/custom-ui/pull/8#issuecomment-715391713)).  It was searching for an attribute named "hide attributes" but it was being changed to "Hide attributes" and the look up was case sensitive.  I changed the lookup to lower the case of the found fields so that it would much the case values.  Nothing I can really do to provide screenshots.  This is keeping this functionality in line with pre 0.117 functionality.

**Comment by Mariusthvdb** [comment]
yea, I know, but it was closed because all issues were gone and I don't see that happening anymore? If you're sure this is needed, I can merge, I take it you tested it locally? will do so myself too

**Comment by CAB426** [comment]
I am not sure it is needed.  I saw some of that behavior but it was very difficult to reproduce - wasn't sure if something old was cache or blocking the script.  This is the only thing that differs from 116 to 117, just the case on the attribute.  You can hold off merging it and only pull if it pops back up.

**Comment by Mariusthvdb** [comment]
yes, let's decide on doing that. I've changed back a couple of times, and as it stands this makes no difference to 'with' or 'without' as far as I can see.
On Safari all shows well without, and on Chrome both still show the full unaltered more-info...
All in all it seems there is some work to do but this isnt it?

**Comment by marshn** [comment]
For what it's worth I am seeing the same problem, ie. "More Info" popup items which have been hidden with 'hide_attributes' are still visible when using Chrome & Firefox (and Edge), they are hidden when using Safari.

I believe that this started happening after updating HA to 0.117. 

In all cases I am using Custom-UI  20201024.

**Comment by CAB426** [comment]
It looks like the fields were being padded in Firefox (don't have Safari to test with).  I added in a trim on the same line as the toLowerCase() was added.  Can you give this a shot and see if that clears it up?  It is working for me on Edge, Chrome and Firefox.

**Comment by Mariusthvdb** [comment]
real sorry, but it doesnt fix it:
Chrome
Schermafbeelding 2020-11-03 om 23 35 17
Firefox:
Schermafbeelding 2020-11-03 om 23 36 43

Safari still unharmed:
Schermafbeelding 2020-11-03 om 23 37 32

**Comment by CAB426** [comment]
@Mariusthvdb Thank you for testing!  I have it set to hide all attributes and missed adding in an additional handling of case for actually hiding listed attributes.  I changed my customization to hide only two attributes and tested in Chrome, Edge, and Firefox with the change, and it looks good to me now.  Please give it a go and let me know.  I also updated the version number to 20201103.

**Comment by Mariusthvdb** [comment]
yep, that works locally in Chrome and Firefox to now, thanks!
I'll merge this, but also want to change the inspector recognizability by using this
```
console.info(
`%c  CUSTOM-UI (JS)  \n%c  Version 20201103 adapted for HA110+  `,
    'color: gold; font-weight: bold; background: black',
    'color: white; font-weight: bold; background: steelblue', );
```
to get this:

Schermafbeelding 2020-11-04 om 08 25 36

reflecting my main state template coloring either steel blue or gold ;-)
will you add that, so we can do this in 1 go? otherwise I'll first merge and then add this too myself.

**Pull request merged**
