### PR TITLE
Fix of warnings and errors popping into the log

### PR DESCRIPTION
**Pull request by SupremeSports**
Hi, this fixes the error saying "Uncaught TypeError: e.push is not a function". This was generating dozens of errors.
- Fixed at line #1312 by adding a catch/try)
- Fixes https://github.com/andrey-git/home-assistant-custom-ui/issues/181

Tested on my HA and works great, please ensure it works with everything Custum-UI is supposed to do as I only use it in yaml.

### CODE REVIEW

**Comment by SupremeSports** [comment]
errors

**Comment by SupremeSports** [comment]
Bad news... after 12 hours without any "Uncaught TypeError: e.push is not a function", it came back :'(

**Comment by Mariusthvdb** [comment]
too bad.

btw, this:
```
 Cannot read property 'state' of undefined" or "Uncaught TypeError: Cannot read property 'attribute' of undefined
```

is not an error in the custom-ui, it is the user not defining the templates correctly.... always have them check for state/existence , or not being none..

you should use that error as feedback to improve your templates ;-)

**Comment by SupremeSports** [comment]
Sorry, It worked, I'm not on the same computer and I had to do a Ctrl+F to clear cache, it works :D

**Comment by SupremeSports** [comment]
> 

> you should use that error as feedback to improve your templates ;-)

Ok, but I don't understand from where comes those errors :(

**Comment by SupremeSports** [comment]
> please take out that 'fix' since it isn't.

Removed the 'Fix', keeping only the e.puch error

**Comment by SupremeSports** [comment]
24 hours now without issues 🤗

**Comment by Mariusthvdb** [comment]
these errors only happen when browsing the settings tab in the left side menu. Did you check that?

**Comment by Mariusthvdb** [comment]
edit the file manually after successfully testing locally, so closing this PR to avoid version conflicts or multiple edit errors.
Many thanks!

**Comment by SupremeSports** [comment]
> these errors only happen when browsing the settings tab in the left side menu. Did you check that?
> will test locally too.
> thanks

Absolutely, I had these errors only in those cases. Tested and fixed for me

**Pull request closed without merging**
