### PR TITLE
More readable code

### PR DESCRIPTION
**Pull request by bratanon**
This PR is a more readable version if #50 .

I think it will be more easy to apply fixes in the future with more readable code that is not obscurified/minified like the current one are.

### CODE REVIEW

**Comment by bratanon** [comment]
See #50

**Comment by Mariusthvdb** [comment]
thanks fir the effort, I did wish we had a non minified version. As explained, I hacked into the final code, and didnt really build it from the source files.

Until I get positive feedback on how to fix this for HA 2022.4 and above, I dont feel there's any profit in trying now though.\
So yes, appreciated, and I agree it would be better.  But different priorities now I am afraid.

Still, if you manage to make the code better and have it behave as it did under 2022.3. Id be happy to test.

**Comment by Mariusthvdb** [comment]
just so you know I did test this, and I must say it does seem to work after all!
```
homeassistant:
  customize:

    input_boolean.test:
      package: Test
      templates:
        icon: >
          return (state === 'on') ? 'mdi:test-tube' : 'mdi:test-tube-off';
        icon_color: >
          return (state === 'on') ? 'gold' : 'green';

    input_number.test_number:
      templates:
        icon_color: >
          if (state == 0) return 'white';
          if (state == 10) return 'yellow';
          if (state == 20) return 'brown';
          if (state == 30) return 'navy';
          if (state == 40) return 'lightblue';
          if (state == 50) return 'green';
          if (state == 60) return 'orange';
          if (state == 70) return 'purple';
          if (state == 80) return 'black';
          if (state == 90) return 'gold';
          return 'red';
```

returns

test-custom-ui


Id be happy if people could test this, so Ill post the new code as a beta and hope for some feedback.

Cant thank you enough for now!

**Comment by bratanon** [comment]
Well, it works until something else changes. I.e. there is a state update from the websocket.
It will then revert back to the old icon color, icon, and state.

As I mentioned, when I tried this is a super small env with only 2 sensors, almost like your picture, I got it working. 
However, when testing it on my main setup with a lot of sensors, and when there are more then 10 websocket state updates every second, it went bad.

I have tried to actually see exactly whats changes with 2022.4 in the frontend in order to see why custom-ui is not working anymore, but its quite hard to find. The only thing I can see is an update on HAWS. 

I was under the impression that they did something huge with the frontend, in ordet to support websockets, but as it turned out, there was already websockets for state handling the frontend and has been a really long time. 

So the changes now seems to be that they are only sending a single state on updates, which makes sense, but I cant find that change in the FE anyware. Which also makes no sense why custom-ui is broken.

**Comment by bratanon** [comment]
After some more testing, I get the same results as you. It works for with your config using `input_number` and `input_boolean`.

However, I added a sensor template:

```
template:
  - sensor:
      - name: "Test"
        state: >
          {{ states('input_boolean.test') }} #This is your input_boolean.
```
 And this simple time pattern trigger automation that does nothing expect just triggers every 10 sec. (Which triggers an websocket event).
 
 ```
 alias: Test automation
description: ''
trigger:
  - platform: time_pattern
    seconds: /10
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
mode: single
```

The `input_number` and `input_boolean` works, but the template sensor is reverted back after every automation trigger.

**Comment by Mariusthvdb** [comment]
I will check that, though at first sight everything still works as hoped for.

Btw with the minified'old' custom-ui and the new ha 2022.4 we also noticed a difference between legacy format template sensors and template: sensors see https://github.com/Mariusthvdb/custom-ui/issues/48#issuecomment-1095334318

Maybe this is related/caused by the same underlying reason.

It was remarkable at least to experience this in the first place and warrants further exploration per se.

**Comment by bratanon** [comment]
Without state templating, it seems to work much better as you say.  Also the legacy templating works more stable the the "new" one. 

I will continue to test this.

**Comment by Mariusthvdb** [comment]
yep. just so you know, that was alreadynoit recommended in [Andrey's](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/templates.md#special-attributes) days..

so the big question is, why does the code work in the new 'readable' version, and needs a page reload in the minified version?

**Comment by bratanon** [comment]
Have made some more cleanup and it seems to work now when not using state templating.

Peek 2022-04-18 14-33

**Comment by Mariusthvdb** [comment]
great. could you add that to a final PR, so  I can merge and release?

**Comment by bratanon** [comment]
Added it now. 

However, I would like to try to find a way to handle state templating aswell as I have been using that for a long time. 
It might not work, and then what we have now is good to go I would say. 

I dont know if there are many others that are using state templating, but if the majority is not, then I guess we can release what we have now, then maybe add a state templaing fix if its possible.

**Pull request merged**
