### PR TITLE
Fix for hide attributes in more-info for Lovelace

### PR DESCRIPTION
**Pull request by CAB426**

### CODE REVIEW

**Comment by CAB426** [comment]
This [commit](https://github.com/Mariusthvdb/custom-ui/pull/8/commits/728d15ae52a89417a6eb6e0b4ea63567c9ffe257) shows the before/after better than any screenshot could.

**What it does:**
This attaches to the hass-more-info event.  Once that event fires, it starts a loop (updateMoreInfo) that waits for the elements to be created (It breaks after 2 iterations, that may need to be adjusted).  Once the elements are found, it finds all the "data-entry" divs, which are the attributes listed in `more-info`.  It cycles through those divs to find that `key` which equates to the name of the attribute.  If that is found in the config file, it removes the parent div to that value which clears the key and value of the attribute.

**What you would prefer:**
I can give it a shot of pulling from the customize.yaml, but no promises that will work.  I will have to wait until the `more-info` is created, find the corresponding attribute and then cycle through each div again.  It may work, but be visible on the screen for a longer period of time than the above solution.  This was trying to get back to the original functionality of customizer and at least having the option to clean up the attributes from `more-info`.

**Comment by CAB426** [comment]
My new commit removed Customizer as a requirement.  Attributes to be hidden are now set in customize.yaml and customize_glob.yaml. If `hide_attributes` is set in YAML, the `hide attributes` node will automatically be hidden, does not need to be explicitly defined.  `all` is a valid option to hide all attributes.

Example (customize.yaml):
```
input_boolean.development:
  hide_attributes:
    - editable
```

Example (customize_glob.yaml):
```
"*.*":
  hide_attributes:
    - all
```

I made a few changes in this file.: 

- I removed the `useCustomizer()` function.
- I removed the `useCustomizer()` call on `init()`, replaced that with the listener for my new function: `window.addEventListener("hass-more-info", window.customUI.updateMoreInfo)` 
- I added my new function: `updateMoreInfo` which is what handles the hiding of attributes.  I changed this from removing the `div` to changing them to setting the display style to `none`.

**Comment by Mariusthvdb** [comment]
Hey!
Thanks for your efforts, you seem to be on a roll ;-)
Still, since you are frequently updating new changes, I am a bit hesitant to merge. Especially since 113 HA apparently has new ways for more-info and these commits are not compatible.

We have to make sure all is well going onward, so I’ll wait for that.

Since you’re at it, maybe you could have a look in inspector and check for the documented error when landing the configuration page in HA?

Thanks!

**Comment by Mariusthvdb** [comment]
latest version seems to work, but also hides attributes from attribute_templates of regular template sensors, which is not good. If anything, the hide_attributes should only hide the templates used in custom_ui, not the attributes themselves.

**Comment by Mariusthvdb** [comment]
checked alright after all, so I guess ready to merge? 
Unless you are still working on this, maybe other details? Let me know and I will write-up the text for the readme and merge tonight ok?
huge thanks!

**Comment by CAB426** [comment]
Just updated the README to include instructions.  Please feel free to make any changes you see fit.  I am not the most skilled technical writer on the planet.

**Comment by Mariusthvdb** [comment]
I like your new text.

However, I think it is useful to keep the old text too. More particularly because the new options power of hiding attributes is illustrated by what we had (or didn't have);-)
Ill change accordingly.

**Comment by Mariusthvdb** [comment]
@CAB426 
guess we have to re-open this (or create a new item) since ha 117 has landed in Beta and doesnt like this customizing the more-info....
could you have another look at it please?

**Comment by CAB426** [comment]
Unfortunately, I don't have a dev instance anymore.  I will be a bit behind on this one.  Probably won't update until 0.117.2.

**Pull request merged**
