### PR TITLE
Remove state templating

### PR DESCRIPTION
**Pull request by bratanon**
In HA 2022.4+ state templating is broken at the moment. 

Lets inform the users that are using this feature that its now gone and do not perform the state templating.

We will inform the users with a warning in the console.

image

### CODE REVIEW

**Comment by bratanon** [comment]
See discussion https://github.com/Mariusthvdb/custom-ui/discussions/53

**Review by Mariusthvdb — APPROVED** [review]

**Comment by Mariusthvdb** [comment]
you want me to merge or can you do the honors ;-)

**Comment by Mariusthvdb** [comment]
noticed now: please bump the version number in the resource to todays date? so we can easily track the version and differences

**Comment by Mariusthvdb** [comment]
please open an issue an issue with all config we need to be able to tell

**Comment by ShadyMCShadesen** [comment]
Is this feature gone forever? Had a lot of customizations with states

**Comment by Mariusthvdb** [comment]
you mean templates customizing state:
```
templates:
  state: >
```
or templates based on state:

```
templates:
  icon: >
    if (state === 'on') return 
```

only the former is taken out now

**Comment by bratanon** [comment]
@ShadyMCShadesen I have updated the readme to be more clear about whats working and whats not. Please see the updated README.

**Comment by ShadyMCShadesen** [comment]
> you mean templates customizing state:
> ```
> templates:
>   state: >
> ```
> or templates based on state:
> 
> ```
> templates:
>   icon: >
>     if (state === 'on') return 
> ```
> 
> only the former is taken out now
> 

I have a lot customizations like the first example. I hope this feature comes back in a future version (•‿•)

**Comment by Mariusthvdb** [comment]
It is too conflicting with HA core, and it has always been considered a true ‘hack in the state machine’ . 

If you must change the state, you are better of writing a core template sensor.

**Pull request merged**
