### PR TITLE
Update to handle hiding attributes for group more-info

### PR DESCRIPTION
**Pull request by CAB426**
Update to handle hiding attributes for group more-info and updated version.

Fix for #22

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
yes, that's progress, thanks. cool.

Still, we still have an issue on groups containing groups though. Special case, but not un usual, so if that could be mitigated, it would be very nice.

 I know that was an issue in the core too before, where these groups showed a toggle, instead of the state. The toggle has been fixed, but apparently something in the code still makes this to show  the attributes, temnplatres et all, including the hide_attributes. 
Detail: it makes it show the attributes of the first listed group, (in my case, made out of device_trackers per family member), including the Map of that person.

**Comment by CAB426** [comment]
Can you show an example of this? (YAML would be nice)  I quickly just created a group of two groups and do not get attributes to show.  It is most likely my example as I don't have any nested groups in my setup.

**Comment by Mariusthvdb** [comment]
so sorry, I was mistaken...

it is not about a group of groups, it is about a group of person entities:
```
group:
  daughters:
    name: Daughters
    icon: mdi:human-child
    entities:
      - person.daughter1
      - person.daughter2
      - person.daughter3
      - person.daughter4
```

Schermafbeelding 2020-11-10 om 09 21 47


As said, it might also be a core HA thing, the group showing individual members details on more-info, but for this purpose, at least we should have a look at the attributes showing, while being hidden in the custom-ui.

**Comment by Mariusthvdb** [comment]
any chance you can have a look at this? otherwise we would have to decide on the PR now, would prefer all in 1 go if at all possible.

**Comment by CAB426** [comment]
Can you test what I just pushed?  It adds iteration to dynamically find the nested `node-info-` node under the group and updates the variable used to find the attributes to hide accordingly.  It should handle all entity types under a group dynamically.  The previous change was just focused at a default group type.  That changes depending on entity type.

**Comment by Mariusthvdb** [comment]
Schermafbeelding 2020-11-11 om 23 15 08

must be some error in the file....

**Comment by CAB426** [comment]
That looks like a front end error.  Those chunk files as frontend files.  I am not seeing that same error.  Did you update to 0.118.0b?

**Comment by Mariusthvdb** [comment]
> That looks like a front end error. Those chunk files as frontend files. I am not seeing that same error. Did you update to 0.118.0b?

no it was a glitch on my side, when updating the version number in the resources, I eradicated the type: module.... sorry 😊

**Comment by Mariusthvdb** [comment]
thanks! great job done!

**Comment by Mariusthvdb** [comment]
meanwhile updated the test machine to beta 118.0b0 and though the customizations show in the Frontend as desired (as far as I tested now) the more info returns all attributes and templates once again..

Schermafbeelding 2020-11-12 om 09 05 21
including the Hide attributes. will open a dedicated 118 issue for this.

**Comment by Mariusthvdb** [comment]
new issue for 118 more-info https://github.com/Mariusthvdb/custom-ui/issues/24

**Pull request merged**
